### ISSUE TITLE
AllTalk and Text-Gen-WebUI-ST wierd interaction, generates the image and the .wav file, but it dosn't play the audio

### ISSUE THREAD

**Issue by guispfilho** [Trojaner/text-generation-webui-stable_diffusion#18]
I've just installed the Text-Gen-WebUI-ST , and it seems to be working fine, the problem is the interaction between it and AllTalk.

Here is an example response I received:
_<audio src="file/extensions/alltalk_tts/outputs/Chiharu Yamada_1716068782.wav" controls autoplay></audio>Chiharu's eyes widen in surprise at your response, but she quickly recovers and smiles reassuringly Don't worry, I won't bite! She chuckles Let's start with the basics. What got you interested in computers?
[image_correclty_generated]_

AllTalk correctly generates the .wav file, but it doesnt send it alongside the text response and the image. 
And as seem in the example above, the text is ouputting the .wav file path, and not the "play button".
The correct text would be:
_[PLAY BUTTOM]
Chiharu's eyes widen in surprise at your response, but she quickly recovers and smiles reassuringly Don't worry, I won't bite! She chuckles Let's start with the basics. What got you interested in computers?
[image_correclty_generated]_

I'm running AllTalk as a Text-Gen-WebUI extension, and it's entire ouput into the command windows is:
```
Llama.generate: prefix-match hit
Output generated in 6.15 seconds (10.09 tokens/s, 62 tokens, context 384, seed 1337)
[AllTalk TTSGen] Chiharu's eyes widen in surprise at your response, but she quickly recovers and smiles reassuringly Don't worry, I won't bite! She chuckles Let's start with the basics. What got you interested in computers?
[AllTalk TTSGen] 4.09 seconds. LowVRAM: False DeepSpeed: True
18:46:26-837540 INFO     [SD WebUI Integration] Using stable-diffusion-webui to generate images.
                           Prompt: She chuckles Let's start with the basics. What got you interested in computers, but she
                         quickly recovers and smiles reassuringly Don't worry, <audio
                         src=file/extensions/alltalk_tts/outputs/Chiharu Yamada_1716068782.wav controls
                         autoplay></audio>Chiharu's eyes widen in surprise at your response, I won't bite, sscore_9,
                         score_8_up, score_7_up, score_6_up, realistic, realism, source_anime, High-Res, High Quality,
                         (masterpiece, best quality, highly detailed, realistic, beautiful eyes, detailed face), BREAK red
                         eyes, red glasses, brown hair, pony tails, long hair, bangs, smiling, lab coat, black boots, ankle
                         boots, blue nails, blue lipstick, cowboy shot, upper body shot
                           Negative Prompt: score_4_up, score_5_up,low detailed, ugly face, bad hands, bad fingers, mutated
                         hands, low res, blurry face, monochrome, words, artist signature, close up
```

And here is Stable-Difussion ouput:

```
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  10816.615869522095
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  7648.261171340942
Moving model(s) has taken 1.81 seconds
To load target model SDXL
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  9031.173444747925
[Memory Management] Model Memory (MB) =  4897.086494445801
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  3110.086950302124
Moving model(s) has taken 3.24 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.93it/s]
Memory cleanup has taken 3.36 seconds██████████████████████████████████████████████████| 15/15 [00:04<00:00,  2.97it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 15/15 [00:08<00:00,  1.77it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 15/15 [00:08<00:00,  2.97it/s]
```

And this is my "settings.yaml" file:

```
preset: Debug-deterministic
seed: 1337
truncation_length: 32768
stream: false
character: Chiharu Yamada
default_extensions:
- openai
- send_pictures
- sd_api_pictures
- gallery
- long_replies
- whisper_stt
- alltalk_tts
- stable_diffusion
alltalk_tts-voice: '#Scarlett_voice_preview (enhanced).wav'
stable_diffusion-api_username: ''
stable_diffusion-api_password: ''
stable_diffusion-base_prompt: sscore_9, score_8_up, score_7_up, score_6_up, realistic, realism, source_anime, High-Res, High Quality, (masterpiece, best quality, highly detailed, realistic, beautiful eyes, detailed face), BREAK red eyes, red glasses, brown hair, pony tails, long hair, bangs, smiling, lab coat, black boots, ankle boots, blue nails, blue lipstick, cowboy shot, upper body shot
stable_diffusion-base_negative_prompt: score_4_up, score_5_up,low detailed, ugly face, bad hands, bad fingers, mutated hands, low res, blurry face, monochrome, words, artist signature, close up,
stable_diffusion-sampler_name: Euler a
stable_diffusion-sampling_steps: 15
stable_diffusion-width: 1024
stable_diffusion-height: 1024
stable_diffusion-cfg_scale: 4
stable_diffusion-clip_skip: 2
stable_diffusion-debug_mode_enabled: true
stable_diffusion-trigger_mode: continuous
stable_diffusion-tool_mode_force_json_output_enabled: false
stable_diffusion-tool_mode_force_json_output_schema: "{\n  \"type\": \"array\", \n  \"items\": {\n    \"type\": \"object\",\n    \"properties\": {\n      \"tool_name\": {\n        \"type\": \"string\",\n        \"required\": true\n      },\n      \"parameters\": {\n        \"type\": \"object\",\n        \"required\": true\n      }        \n    },\n    \"additionalProperties\": false\n  },\n  \"minItems\": 1\n}"
stable_diffusion-interactive_mode_input_trigger_regex: .*(draw|paint|create|send|upload|add|show|attach|generate)\b.+?\b(image|pic(ture)?|photo|snap(shot)?|selfie|meme)(s?)
stable_diffusion-interactive_mode_output_trigger_regex: .*[*([]?(draws|paints|creates|sends|uploads|adds|shows|attaches|generates|here (is|are))\b.+?\b(image|pic(ture)?|photo|snap(shot)?|selfie|meme)(s?)
stable_diffusion-interactive_mode_description_prompt: |
  You are now a text generator for the Stable Diffusion AI image generator. You will generate a text prompt for it.
  Describe [subject] using comma-separated tags only. Do not use sentences. Include many tags such as tags for the environment, gender, clothes, age, location, light, daytime, angle, pose, etc.
  Very important: only write the comma-separated tags. Do not write anything else. Do not ask any questions. Do not talk.
stable_diffusion-dont_stream_when_generating_images: false
stable_diffusion-generation_rules:
- regex: .*\b(detailed)\b
  match:
  - input
  - output
  actions:
  - name: prompt_append
    args: '(high resolution, detailed, realistic, vivid: 1.2), hdr, 8k, <lora:add_details:1>'
- regex: ^Assistant$
  match:
  - character_name
  actions:
  - name: prompt_append
    args: 
  - name: negative_prompt_append
    args: 
- regex: ^Example$
  match:
  - character_name
  actions:
  - name: faceswaplab_enable
  - name: faceswaplab_set_source_face
    args: file:///{STABLE_DIFFUSION_EXTENSION_DIRECTORY}/assets/example_face.jpg
stable_diffusion-hires_sampling_steps: 10
stable_diffusion-faceswaplab_source_face: file:///{STABLE_DIFFUSION_EXTENSION_DIRECTORY}/assets/example_face.jpg
stable_diffusion-reactor_source_face: file:///{STABLE_DIFFUSION_EXTENSION_DIRECTORY}/assets/example_face.jpg
stable_diffusion-reactor_source_gender: none
stable_diffusion-reactor_target_gender: none
stable_diffusion-faceid_source_face: file:///{STABLE_DIFFUSION_EXTENSION_DIRECTORY}/assets/example_face.jpg
stable_diffusion-ipadapter_reference_image: file:///{STABLE_DIFFUSION_EXTENSION_DIRECTORY}/assets/example_face.jpg
```

If someone could give me a help on this, I'll appreciate a lot. Thank you.

**Comment by Trojaner** [comment]
Hello, can you try with https://github.com/Trojaner/text-generation-webui-stable_diffusion/commit/50c615149300901135bcbdb3a301b0ec856c3920 ? (just update the extension)

**Comment by guispfilho** [comment]
Working now! Thank you very for the fast response!

And if I could bother you with another question. If I understood right, the Continuous mode of generation, if set to "Genereted Text" will use the regex rules set by the user at the bottom of the settings.yaml:

```
stable_diffusion-generation_rules:
  # Add details to the prompt if the input text or output text contains the word "detailed".
  - regex: .*\b(detailed)\b
    match: ["input", "output"]
    actions:
      - name: "prompt_append"
        args: "(high resolution, detailed, realistic, vivid: 1.2), hdr, 8k, <lora:add_details:1>"
```

So if I set it to Continuous + Generated Text, I have to extent these rules, like:

```
  - regex: .*\b(drinking)\b
    match: ["input", "output"]
    actions:
      - name: "prompt_append"
        args: "drinking, holding glass"
```

Is that correct? If so, using the regex format above is correct, in order to create AND statements within OR statements?

`(?=.*\b"yellow car"\b)(?=.*\b"yellow car"\b).*|(?=.*\b"green house"\b)(?=.*\b"red house"\b).*`

In the example above, it would return positive if the input/output text have both "yellow car" AND blue car", OR both "green house" AND "red house".

Does this extension works like that?

**Comment by Trojaner** [comment]
Regex rules are always applied regardless of mode used.

The regex you have posted has minor errors. I will assume the second yellow car was supposed to be blue car:
1. remove quotes unless you explicitly wants the words to be wrapped by quotes in the output
2. You should wrap both cases with parentheses:
`((?=.*\byellow car\b)(?=.*\byellow car\b).*)|((?=.*\bgreen house\b)(?=.*\bred house\b).*)`

You can test it here, btw:
https://regex101.com/

Don't forget to select Python on the left and to use `gmu` as options.

**Comment by guispfilho** [comment]
Oh yes... I miss typed it. Thank you for the information, and I didn't know this site! Awesome.

And the last question I swear... =D 
Would it be possible to use the found regex term as reference to output a word after it?

Something like this:

```
  - regex: .*\b(drinking)\b
    match: ["input", "output"]
    actions:
      - name: "prompt_append"
        args: "drinking \b(detailed)\b\s+(\w+)"
```

I'm pretty sure this would work like that, but something similar to this could be used?
